# Generated by Django 3.2.5 on 2021-10-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acc_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
