# Generated by Django 3.2.5 on 2022-02-19 06:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='id',
            field=models.CharField(default=core.models.gen_pk, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
